;;; -*- buffer-read-only: t -*- vi: set ro: */
;;; Automatically generated by SWIG; do not edit.

(define-module (lapack lapack))


;;; (load-extension "libguile-lapack" "SWIG_init")
(define my-so (dynamic-link "lapack/libguile-lapack.so"))
(dynamic-call "SWIG_init" my-so)


(export gsl-dgesv
        gsl-zgesv
        gsl-dgels
        gsl-zgels)
